[project]
name = "simplifypypatterns"
version = "0.1.0"
description = "Python Simplicity Patterns"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "hypothesis>=6.142.4",
    "pandas>=2.0.0",
    "pytest>=8.4.2",
    "typeguard>=4.4.4",
]
